import type { components } from "@/types/api";

type RecipeContext = components["schemas"]["RecipeContext"];

export const recipeContextFixture: RecipeContext = {
  current_step: 0,
  cooking_started: false,
  scaled_servings: null,
  checked_ingredients: [],
  recipe: {
    title: "Spaghetti al Pomodoro",
    description: "A classic Italian pasta with a simple, bright tomato sauce.",
    servings: 4,
    original_servings: 4,
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    difficulty: "easy",
    cuisine: "Italian",
    dietary_tags: ["vegetarian"],
    ingredients: [
      {
        name: "spaghetti",
        quantity: 400,
        unit: "g",
        preparation: null,
        category: "pantry",
        substitutes: ["linguine", "bucatini"],
      },
      {
        name: "canned whole tomatoes",
        quantity: 400,
        unit: "g",
        preparation: "crushed by hand",
        category: "pantry",
        substitutes: ["fresh tomatoes"],
      },
      {
        name: "garlic",
        quantity: 2,
        unit: "cloves",
        preparation: "thinly sliced",
        category: "produce",
        substitutes: [],
      },
      {
        name: "extra virgin olive oil",
        quantity: 4,
        unit: "tbsp",
        preparation: null,
        category: "pantry",
        substitutes: [],
      },
      {
        name: "fresh basil",
        quantity: null,
        unit: null,
        preparation: "torn",
        category: "produce",
        substitutes: ["dried basil"],
      },
      {
        name: "salt",
        quantity: null,
        unit: "to taste",
        preparation: null,
        category: "spice",
        substitutes: [],
      },
    ],
    steps: [
      {
        step_number: 1,
        instruction: "Bring a large pot of water to a boil. Season generously with salt.",
        duration_minutes: 10,
        timer_label: "Boil water",
        requires_attention: false,
        tips: ["Use about 1 tbsp of salt per litre of water"],
      },
      {
        step_number: 2,
        instruction: "Heat olive oil in a wide pan over medium heat. Add garlic and cook until golden and fragrant, about 1 minute.",
        duration_minutes: 1,
        timer_label: "Cook garlic",
        requires_attention: true,
        tips: ["Remove garlic before it browns to avoid bitterness"],
      },
      {
        step_number: 3,
        instruction: "Add crushed tomatoes to the pan. Simmer over medium-low heat for 15 minutes, stirring occasionally.",
        duration_minutes: 15,
        timer_label: "Simmer sauce",
        requires_attention: false,
        tips: ["Season with salt halfway through simmering"],
      },
      {
        step_number: 4,
        instruction: "Cook spaghetti in the boiling water until al dente, 8-10 minutes. Reserve a cup of pasta water before draining.",
        duration_minutes: 9,
        timer_label: "Cook pasta",
        requires_attention: false,
        tips: ["Check the packet for the recommended cooking time"],
      },
      {
        step_number: 5,
        instruction: "Drain the pasta and toss it in the sauce over low heat for 1 minute. Add a splash of pasta water if needed. Finish with torn basil.",
        duration_minutes: 1,
        timer_label: null,
        requires_attention: false,
        tips: ["Pasta water helps the sauce cling to the spaghetti"],
      },
    ],
  },
};
